# Generated by Django 6.1.1 on 2026-09-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datos_diagrama',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
