# Generated by Django 6.1.1 on 2026-09-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_datos_diagrama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcollaborator',
            options={'verbose_name': 'Detalle de Proyecto', 'verbose_name_plural': 'Detalles de Proyecto'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='proyecto',
        ),
        migrations.AlterModelTable(
            name='projectcollaborator',
            table='detalle_proyecto',
        ),
    ]
