# Generated by Django 6.1.1 on 2026-09-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pos_x', models.FloatField(default=100.0)),
                ('pos_y', models.FloatField(default=100.0)),
                ('width', models.FloatField(default=200.0)),
                ('is_abstract', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='projects.project')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('association', 'Asociación'), ('inheritance', 'Herencia'), ('composition', 'Composición'), ('aggregation', 'Agregación'), ('dependency', 'Dependencia'), ('realization', 'Realización')], default='association', max_length=20)),
                ('multiplicity_source', models.CharField(blank=True, default='', max_length=10)),
                ('multiplicity_target', models.CharField(blank=True, default='', max_length=10)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='diagrams.diagramclass')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='diagrams.diagramclass')),
            ],
            options={
                'verbose_name': 'Relación',
                'verbose_name_plural': 'Relaciones',
            },
        ),
        migrations.CreateModel(
            name='ClassMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('return_type', models.CharField(default='void', max_length=100)),
                ('visibility', models.CharField(choices=[('+', 'Public'), ('-', 'Private'), ('#', 'Protected'), ('~', 'Package')], default='+', max_length=1)),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('diagram_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='diagrams.diagramclass')),
            ],
            options={
                'verbose_name': 'Método',
                'verbose_name_plural': 'Métodos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_type', models.CharField(default='String', max_length=100)),
                ('visibility', models.CharField(choices=[('+', 'Public'), ('-', 'Private'), ('#', 'Protected'), ('~', 'Package')], default='-', max_length=1)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('diagram_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='diagrams.diagramclass')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
